In [5]:
import numpy as np
my_list = [10, 20, 30]

arr = np.array(my_list)

print(arr.dtype)
print(arr.shape)

int32
(3,)


In [6]:
a =  np.array([[1, 2, 3,4,5,6],[7,8,9,10,11,12]]) 
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:

print(a.shape)

(2, 6)


In [8]:
import numpy as np

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:

np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:

arr1 = np.random.randint(1, 10, 6).reshape(2, 3)
arr2 = np.random.randint(1, 10, 6).reshape(2, 3)

print(arr1)
print(arr2)

print(arr1 >= arr2)

In [11]:
arr1 = np.random.randint(1, 10, 6).reshape(2, 3)

In [12]:
arr1

array([[1, 2, 4],
       [6, 5, 7]])

In [13]:
arr2 = np.random.randint(1, 10, 6).reshape(2, 3)

In [14]:
arr2

array([[8, 4, 9],
       [2, 4, 4]])